config/routes.rb
PacerMateApp::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :horses, only: [:create, :destroy]

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/models/horse.rb
# == Schema Information
#
# Table name: horses
#
#  id          :integer         not null, primary key
#  racing_name :string(255)
#  stable_name :string(255)
#  sex         :integer
#  colour      :string(255)
#  foal_date   :date
#  user_id     :integer
#  created_at  :datetime        not null
#  updated_at  :datetime        not null
#

class Horse < ActiveRecord::Base
  attr_accessible :colour, :foal_date, :racing_name, :sex, :stable_name

  belongs_to :user

  validates :user_id, presence: true
  validates :stable_name, presence: true, length: { maximum: 100 }
  validates :racing_name, length: { maximum: 255 }

  default_scope order: 'horses.stable_name'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer         not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime        not null
#  updated_at      :datetime        not null
#  password_digest :string(255)
#  remember_token  :string(255)
#  admin           :boolean         default(FALSE)
#

class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password

  has_many :horses, dependent: :destroy
  
  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token
  
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, 
            uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  
  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/horses_controller.rb
class HorsesController < ApplicationController
  before_filter :signed_in_user, only: [:create, :destroy]

  def index
  end

  def create
    @horse = current_user.horses.build(params[:horse])
    if @horse.save
      flash[:success] = "Horse created!"
      redirect_to root_path
    else
      render 'static_pages/home'
    end
  end

  def destroy
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
	end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @horse = current_user.horses.build if signed_in?
  end

  def help
  end

  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_filter :correct_user,   only: [:edit, :update]
  before_filter :admin_user,     only: :destroy
  
  def index
    @users = User.paginate(page: params[:page])
  end
  
  def show
    @user = User.find(params[:id])
    @horse = @user.horses.build
    @horses = @user.horses.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Pacer Mate!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_path
  end

  private

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Pacer Mate"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    current_user = user
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    @current_user ||= user_from_remember_token
  end

  def current_user?(user)
    user == current_user
  end
  
  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_path, notice: "Please sign in."
    end
  end
  
  def sign_out
    current_user = nil
    cookies.delete(:remember_token)
  end
  
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end

  def store_location
    session[:return_to] = request.fullpath
  end

  private

    def user_from_remember_token
      remember_token = cookies[:remember_token]
      User.find_by_remember_token(remember_token) unless remember_token.nil?
    end
    
    def clear_return_to
      session.delete(:return_to)
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/horses/_horse.html.erb
<li>
  <span class="content"><%= horse.stable_name %></span>
  <span class="timestamp">
    Added <%= time_ago_in_words(horse.created_at) %> ago.
  </span>
</li>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="/">&copy; Pacer Mate <%= Time.now.year %></a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="#">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "pacer mate", root_path, id: "logo" %>
      <nav>
        <!-- <ul class="nav pull-left">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#">Link</a></li>
          <li><a href="#">Link</a></li>
          <li><a href="#">Link</a></li>
        </ul> -->
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <% if signed_in? %>
            <li><%= link_to "My Stable", current_user %></li>
          <% end %>
          <li><a href="#">Gear Database</a></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <%# if current_user.admin? %>
                  <li class="divider"></li>
                  <li class="nav-header">Admin Tasks</li>
                  <li><%= link_to "Users", users_path %></li>
                <%# end %>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
        <form class="navbar-search pull-right" action="">
          <input type="text" class="search-query span2" placeholder="Search">
        </form>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
    
    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-31997702-1']);
      _gaq.push(['_trackPageview']);
      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>
    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_horse_form.html.erb
<%= form_for @horse, :html => { :class => "form-horizontal", :id => "horse_form", :style => "padding-left:20px" } do |f| %>

  <%= render 'shared/error_messages', object: f.object %>

  <fieldset>

    <div class="control-group">
      <%= f.label :stable_name, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :stable_name, :class => "input-xlarge" %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :racing_name, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :racing_name, :class => "input-xlarge" %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :sex, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :sex, :class => "input-xlarge" %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :colour, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :colour, :class => "input-xlarge" %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :foal_date, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :foal_date, :class => "input-xlarge" %>
      </div>
    </div>

  </fieldset>

<!-- 
  <div class="field">

    <%= f.label :stable_name %>
    <%= f.text_field :stable_name %>

    <%= f.label :racing_name %>
    <%= f.text_field :racing_name %>

    <%= f.label :sex %>
    <%= f.text_field :sex %>

    <%= f.label :colour %>
    <%= f.text_field :colour %>

    <%= f.label :foal_date %>
    <%= f.text_field :foal_date %>

  </div>
 -->
  <%= f.submit "Post", class: "btn btn-primary" %>

<% end %>

<!-- <form class="form-horizontal">
  <fieldset>
    <legend>Legend text</legend>
    <div class="control-group">
      <label class="control-label" for="input01">Text input</label>
      <div class="controls">
        <input type="text" class="input-xlarge" id="input01">
        <p class="help-block">Supporting help text</p>
      </div>
    </div>
  </fieldset>
</form> -->

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size: 52 %>
</a>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.horses.count, "horse") %>
</span>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  ...
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  ...
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  ...
</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/horse_form' %>
      </section>
    </aside>
  </div>  
<% else %>
	<div class="center hero-unit">
	  <h1>Welcome to Pacer Mate</h1>

	  <h2>
	    This is a helper application for those in the horse pacing industry.
      <br><br>
      It will provide training tracking tools, gear advice and horse history, along with a blog of useful information.
      <br><br>
      This application is very much in development, and is not currently ready for use. I will regularly be deleting data until the site hits beta stage.
	  </h2>

	  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
	</div>

	<%#= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>
<% end %>

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :email %>
<%= f.text_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation, "Confirm Password" %>
<%= f.password_field :password_confirmation %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete, confirm: "You sure?" %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %> 
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
  <%= form_for(@user) do |f| %>  
      <%= render 'fields', f: f %>
      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails" target="_blank">change</a>
  </div>
</div>

app/views/users/index.html.erb
<%= provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<%= provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">

  <div class="span8">

    <% if @user.horses.any? %>
      <h1 style="display:inline">
        My Stable (<%= @user.horses.count %>) 
      </h1>
      
      <% if signed_in? && current_user?(@user) %>
        <a data-toggle="modal" href="#myModal" class="btn btn-primary" style="margin: 0 0 20px 20px">Add Horse</a>
      <% end %>
      <ol class="horses">
        <%= render @horses %>
      </ol>
      <%= will_paginate @horses %>
    <% end %>

  </div>

  <aside class="span4">
    <section>
      <h2>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h2>
    </section>
  </aside>

</div>

<div id="myModal" class="modal hide fade span4">

  <div class="modal-header">
    <button class="close" data-dismiss="modal">&times;</button>
    <h3>Add Horse</h3>
  </div>

  <div class="modal-body">

    <!-- <h4>Details</h4> -->

    <%= render 'shared/horse_form' %>

  </div>

  <div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal" >Close</a>
    <a href="#" class="btn btn-primary">Save changes</a>
  </div>

</div>